put ImageRectangle(image:"name") into NR
put NR+(-140,32,120,30) into ReadNameR


repeat forever
	put ReadText(ReadNameR) into Name
	log Name
	put ReadNameR + (0,27,0,27) into ReadNameR
	
	if (name <> Pervious_name)
		put name into Pervious_name
	else
		logwarning "Already Ready this"
		Exit repeat
	end if
	
	(*if repeatindex() = 20 then
		LogError "To Much Scrolling"
		exit repeat
	end if*)
	
end repeat
