

Click "Start"
Click "Web Bowser Icon"
WaitFor 3.5, "Refresh Icon"
Click Image:"Magnifying Glass"

//--Turn On Usability Mode 
set the usabilityMode to True
//--Turn on Usability Load Time Warning
set the usability_LoadTimeWarning to 7 seconds


TypeText "www.eggplant.io"
TypeText returnKey
WaitFor 5.0, "Eggplant Logo"
WaitFor 3.5, "Refresh Icon"

//--Turn Off Usability Mode 
set the usabilityMode to False
