
put <<cd /Users/randyhesse/Documents/Simple_Examples/facial_recognition.suite/Resources/ && >> into CDVAR

//put <</Users/randyhesse/Documents/Simple_Examples/facial_recognition.suite/Resources/Test.go>> into var1

put <</usr/local/bin/go run >> into vargo


put <</Users/randyhesse/Documents/Simple_Examples/facial_recognition.suite/Resources/Test.go>> into var1


put (CDVAR & vargo & var1) into varOUT


log varOUT


log shell(varOUT)