----------------DO Not Touch--------------------------------------
set GD to a new "GlobalDefine"
-------------------------------------------------------------------------
(GD).SetupFiles "/Users/randyhesse/Documents/Simple Examples/Data Driven/Version 3/PatientInformation.csv"


Run (GD).BuildPatient 10
log global patient
log global patient.MedicalRecordNumber




-------------------------------------------------------------------------

log (GD).PatientCount
log (GD).ColumnNames
------------------------------
put (GD).GETALL ("Medical Record Number") into  VARS
log VARS
