----------------DO Not Touch--------------------------------------
set GD to a new "Modules/GlobalDefine"
-------------------------------------------------------------------------
-------------------------------------------------------------------------
-------------------------------------------------------------------------
-----------Code Below can be altered--------------------------
---Patient Information Setup-------------------------------------
(GD).SetupFiles "/Users/randyhesse/Documents/Simple Examples/Data Driven/Version 3/PatientInformation.csv"
-------------------------------------------------------------------------

---For setting up Multi User----------------------------------------------------------------------
--(GD).SetupEnvironment "/Users/randyhesse/Documents/Simple Examples/Data Driven/Version 3/EnvironmentConfig.csv"
--Run (GD).GetUser 4
--RunWithNewResults "Libraries/Login"
-------------------------------------------------------------------------


--RunWithNewResults "States/Zero" 


repeat (GD).PatientCount times
	
	--Run "Test/A"
	--Run "Test/B"
	Run (GD).BuildPatient repeatindex()+1
	RunWithNewResults "Test/NewPatient"
	
end repeat

Run "Libraries/Logout"
Run "States/Zero"






