----------------DO Not Touch--------------------------------------
set GD to a new "Modules/GlobalDefine"
-------------------------------------------------------------------------
(GD).SetupFiles "/Users/randyhesse/Documents/Simple Examples/Data Driven/Version 3/PatientInformation.csv"
(GD).SetupEnvironment "/Users/randyhesse/Documents/Simple Examples/Data Driven/Version 3/EnvironmentConfig.csv"
-------------------------------------------------------------------------





put (GD).GetUser (4) into UserInformation

log  UserInformation
log  UserInformation.username
log  UserInformation.password
-------------------------------------------------------------------------

put (GD).BuildPatient (10) into patient
log  patient
log  patient.MedicalRecordNumber

-------------------------------------------------------------------------


put (GD).GetUser (2) into Patient
log Patient



put (GD).BuildPatient (2) into Patient
log Patient
