//Based onRun "Example Post Json"


put file "/Users/randyhesse/Desktop/WebFormData6.csv" into var

log var


put JSONFormat({"Foot":"shake"}) into requestbody




Example_OverLoad(httpMethod:"POST",url:"https://postman-echo.com/post",requestBodyFormat:"JSON (application/json)",requestBody:requestbody)


put JSONValue(api().responseBody) into responseBody

log api().statusCode
log responseBody.data