

put (645,460,729,491) into SR

put (item 3 of Sr - item 1 of SR)+1 into XLength
put (item 4 of Sr - item 2 of SR)+1 into YLength

put (item 1 of SR , item 2 of SR) into StartPoint
put (item 1 of SR , item 2 of SR) into StartPointReset

repeat YLength times
	repeat XLength times
		
		log StartPoint && ColorAtLocation(StartPoint)
		
		put (1,0) + StartPoint into StartPoint
	end repeat
	
	put item 1 of StartPointReset into item 1 of StartPoint
	put (0,1) + StartPoint into StartPoint
end repeat
