----------------DO Not Touch--------------------------------------
set GD to a new "Modules/GlobalDefine"
-------------------------------------------------------------------------
(GD).SetupCustomFile "/Users/randyhesse/Documents/Simple Examples/Data Driven/Version 3/PatientInformation.csv"
(GD).SetupEnvironment "/Users/randyhesse/Documents/Simple Examples/Data Driven/Version 3/EnvironmentConfig.csv"
-------------------------------------------------------------------------





put (GD).GetUser (4) into UserInformation
log  UserInformation.username
log  UserInformation.password
-------------------------------------------------------------------------
put (GD).GetPatient  (10) into patient
log  patient
log  patient.MedicalRecordNumber




-------------------------------------------------------------------------

log (GD).PatientCount
log (GD).ColumnNames
------------------------------
put (GD).GETALL ("Medical Record Number") into  VARS
log VARS


log (GD).GETALL ("First Name")