moveto imagelocation("English Name")+(0,-100)

put EveryImageLocation("LineRow") into LineImage
put the number of items of LineImage into Max

repeat MAX times
	
	put item repeatindex() of LineImage into PointXY
	insert PointXY+(100,-10) into ReadSquare
	insert PointXY+(200,10) into ReadSquare
	
	put readtext(ReadSquare) into PokemonName
	log PokemonName
	if PokemonName = "pidgey" then
		moveto PointXY+(165,-5)
		Exit repeat
	else
		--
	end if
	
	
	put () into ReadSquare
	
end repeat
