
put ("spanish","german","japanese","latin","french") into langlist
put the number of items of langlist into max

repeat max times
	
	
	
	put item repeatindex() of langlist into Langg
	//put "spanish" into langg
	put "Good Evening" into phrase
	
	Click "Text"
	TypeText controlKey & "a"
	TypeText deleteKey
	
	
	TypeText phrase
	
	Click item 2 of EveryImageLocation("Arrow")
	
	
	
	
	click text:Langg,SearchRectangle:("LangTL","LangBR")
	log ReadText(("TL","BR"),language:langg)
	
	
end repeat
