----------------DO Not Touch--------------------------------------
set GD to a new "Modules/GlobalDefine"
-------------------------------------------------------------------------
(GD).SetupFiles "/Users/randyhesse/Documents/Simple Examples/Data Driven/Version 3/PatientInformation.csv"
(GD).SetupEnvironment "/Users/randyhesse/Documents/Simple Examples/Data Driven/Version 3/EnvironmentConfig.csv"
-------------------------------------------------------------------------





Run (GD).BuildPatient 2
log global Patient




log (GD).PatientCount
log (GD).ColumnNames
log (GD).ColumnCount

------------------------------
put (GD).GETALL ("Medical Record Number") into  ALLMRNS
log ALLMRNS


log (GD).DataDump


