on initialize

	put new "Example03/Class02"  into my CS2
	
	//put CS2 into my CS2
	
end initialize


Properties
	propertyKey1:"value1",
	propertyKey2:"value2"
end Properties


on C1_Function1
	log "From Class01 Function 01"
end C1_Function1

on C1_Function2
	log "From Class01 Function 02"
end C1_Function2


on C1_Function3
	log "From Class01 Function 03"
end C1_Function3


on C1_Function4 var
	//put (my CS2) into CS2
	(my cs2). C2_Function2 (var)
end C1_Function4


